<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="candidate"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="question">Question</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-xs-12">
    
        <div class="box">
            
            <!--formular pro pridani nove otazky -->
            <?php echo $this->questionForm ?>
            
            <!--button ktery vraci zpet na seznam testu (kdyz uz jsem dokoncil pridavani otazek) -->
            <a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'index'), 'default', true); ?>"><i class="fa fa-files-o"></i> <span> Tests</span></a>

        </div>
      </div>
    </div><!-- /.row (main row) -->

  </section><!-- /.content -->
</div><!-- /.content-wrapper -->