<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
      <small>Control panel</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="index.php"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="question">Otázky</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-xs-12">
        <form role="form">
        <div class="box">

          <div class="box-header with-border">
            <h3 class="box-title">Základné informace</h3>
          </div><!-- /.box-header -->

          <div class="box-body">
            <!-- text input -->
            <div class="row">
              <div class="col-xs-6">
                 <div class="form-group">
                  <label>Otázka</label>
                  <input type="text" class="form-control" placeholder="Enter ...">
                </div>
                <div class="form-group">
                  <label>Typ</label>
                  <select class="form-control">
                    <option>Checkbox - ABC</option>
                    <option>Text - Jednoslovní/Věta</option>
                    <option>Textarea - Více textu</option>
                  </select>
                </div>
                <div class="form-group">
                  <label>Správna odpověd (podle odpovědi)</label>
                  <input type="text" class="form-control" placeholder="Enter ...">
                </div>
              </div>
              <button type="submit" class="btn btn-success btn-md">Uložit</button>
            </div>   
          </div><!-- /.box-body -->

        </div>
        </form>
      </div>
    </div><!-- /.row (main row) -->

  </section><!-- /.content -->
</div><!-- /.content-wrapper -->