<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="candidate"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="candidate">Candidates</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-md-4">
        <div class="box box-primary min-420">
          <div class="box-body box-profile">
            <img class="profile-user-img img-responsive img-circle" src="dist/img/avatar5.png" alt="User profile picture">
            <a>Add file...</a>
            <ul class="list-group list-group-unbordered">
              <li class="list-group-item">
                <b>Last update: </b>
                <a class="pull-right">14. 07. 2015</a>
              </li>

              <li class="list-group-item">
                <b>Interview: </b>
                <a class="pull-right">11. 08. 2015</a>
              </li>

              <li class="list-group-item">
                <b>Status: </b>
                <a class="pull-right">Waiting for response</a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-md-8">
        <div class="box box-primary min-420">
          <div class="box-body box-profile">
            <ul class="list-group list-group-unbordered">
              <li class="list-group-item">
                <b>Firstname: </b>
                <a>Juraj</a>
              </li>
              <li class="list-group-item">
                <b>Surename: </b>
                <a>Kostráb</a>
              </li>
              <li class="list-group-item">
                <b>Birthday: </b>
                <a>11.11.1991</a>
              </li>
              <li class="list-group-item">
                <b>Seniority: </b>
                <a>Junior</a>
              </li>
              <li class="list-group-item">
                <b>Position: </b>
                <a>Developer</a>
              </li>
              <li class="list-group-item">
                <b>Technology: </b>
                <a>.NET</a>
              </li>
              <li class="list-group-item">
                <b>Comment: </b>
                <p>Farm-to-table biodiesel +1 pop-up, freegan before they sold out chia four dollar toast try-hard kogi single-origin coffee. Mlkshk VHS banh mi, readymade fixie twee put a bird on it. Four dollar toast franzen artisan cronut semiotics yuccie, neutra.Farm-to-table biodiesel +1 pop-up.</p>
              </li>
            </ul>
          </div>
        </div>
      </div>
      
      <h1 class="main-h1">Attachements</h1>

      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-body box-profile">
            <b>Upload new file: </b>
            <div class="form-group"><input type="file" id="exampleInputFile"></div>
            <ul class="list-unstyled">
              <li>
                <span>CV.pdf(24.5 Kb)</span> <a>Delete</a>
              </li>
              <li>
                <span>About.pdf(24.5 Kb)</span> <a>Delete</a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <h1 class="main-h1">Tests</h1>

      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-body box-profile">
            
            <form>
              <div class="form-group wdth-300">
                <select multiple class="form-control">
                  <option>Microsof Office</option>
                  <option>Front-End</option>
                  <option>Základy .NET</option>
                  <option>Git-ování</option>
                  <option>Pohoda</option>
                </select>
              </div>
              <button type="submit" class="btn btn-success btn-md">Generate</button>
            </form>
            <div>

              <br><b>Generated: </b>
              <ul class="list-unstyled">
                <li>
                  Microsof Office
                </li>
                <li>
                  Front-End
                </li>
                <li>
                  Základy .NET
                </li>
              </ul> 

            </div>
          </div>
        </div>

        <button type="submit" class="btn btn-danger btn-lg">Delete Candidate</button>
      </div>



    </div><!-- /.row (main row) -->

  </section><!-- /.content -->
</div><!-- /.content-wrapper -->