<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
      <small>Control panel</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="index.php"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="candidate">Kandidáti</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-xs-12">
        <div class="box box-primary">
          <div class="box-body box-profile">
            <img class="profile-user-img img-responsive img-circle" src="dist/img/user4-128x128.jpg" alt="User profile picture">
            <p class="text-muted text-center">Aktualizace: 14-07-2015 | Pohovor: 11-08-2015 | Stav: Čeká na odpověd</p>

            <ul class="list-group list-group-unbordered">
              <li class="list-group-item">
                <b>Jméno a příjmení: </b>Juraj Kostráb
              </li>
              <li class="list-group-item">
                <b>Rok narození: </b>1990
              </li>
              <li class="list-group-item">
                <b>Pozice: </b>Developer
              </li>
              <li class="list-group-item">
                <b>Technológie: </b>.NET, JavaScript, Python
              </li>
              <li class="list-group-item">
                <b>Seniorita: </b>junior
              </li>
              <li class="list-group-item">
                <b>Komentář: </b>
                <p>Farm-to-table biodiesel +1 pop-up, freegan before they sold out chia four dollar toast try-hard kogi single-origin coffee. Mlkshk VHS banh mi, readymade fixie twee put a bird on it. Four dollar toast franzen artisan cronut semiotics yuccie, neutra.</p>
              </li>
            </ul>
          </div><!-- /.box-body -->
        </div>
      </div>
    </div><!-- /.row (main row) -->

  </section><!-- /.content -->
</div><!-- /.content-wrapper -->