<form action="<?php echo $this->element->getAction(); ?>" method="<?php echo $this->element->getMethod(); ?>">
	
	<div class="row">
		<div class="col-md-4">
			<div class="box box-primary min-550">
				<div class="box-body box-profile">
					<img class="profile-user-img img-responsive img-circle" src="<?php echo $this->baseUrl() . "/dist/img/no-avatar.png"; ?>" alt="User profile picture">
					<?php echo $this->element->profilePhoto; ?>
					<div class="form-group">
						<label>Firstname</label>
						<?php echo $this->element->jmeno; ?>
					</div>

					<div class="form-group">
						<label for="prijmeni">Surname</label>
						<?php echo $this->element->prijmeni; ?>
					</div>

					<div class="form-group">
						<label for="datum_narozeni">Birthday</label>
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<?php echo $this->element->datum_narozeni; ?>
						</div><!-- /.input group -->
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-8">
			<div class="box box-primary min-550">
				<div class="box-body box-profile">
					<div class="form-group">
						<label>Interview</label>
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<?php echo $this->element->datum_pohovoru; ?>
						</div><!-- /.input group -->
					</div>

					<div class="form-group">
						<label>Status</label>
						<?php echo $this->element->id_status; ?>
					</div>

					<div class="form-group">
						<label>Position</label>
						<?php echo $this->element->id_pozice; ?>
					</div>

					<div class="form-group">
						<label>Technology</label>
						<?php echo $this->element->kandidat_technologie; ?>
					</div>

					<div class="form-group">
						<label>Seniorrity</label>
						<?php echo $this->element->id_seniorita; ?>
					</div>

					<div class="form-group">
						<label>Comment</label>
						<?php echo $this->element->komentar; ?>
					</div>

				</div>
			</div>
		</div>

		<h1 class="main-h1">Attachements</h1>

		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-body box-profile">
					<b>Upload new file: </b>
					<div class="form-group"><input type="file" id="exampleInputFile"></div>
					<ul class="list-group list-group-unbordered">
						<li class="list-group-item min-42">
							<div class="flleft min-150"><a class="tud" href="#">CV.pdf(24.5 Kb)</a></div>
							<div class="flleft"><a>Delete</a></div>  
						</li>
						<li class="list-group-item min-42">
							<div class="flleft min-150"><a class="tud" href="#">About.pdf(24.5 Kb)</a></div>
							<div class="flleft"><a>Delete</a></div>   
						</li>
					</ul>
				</div>
			</div>

			<?php echo $this->element->Save; ?>
		</div>
	</form>