<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo $this->baseUrl() . "/"; ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="candidate">Candidates</a></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <a href="candidate-edit"><button type="submit" class="btn btn-success">Add new candidate</button></a>       
          </div><!-- /.box-header -->
          
          <!-- Candidate list HEADER-->
          <?php if (count($this->candidates) > 0) {?>
           <div class="box-body">
              <table id="candidates-list" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <!--<th>ID</th>-->
                    <th>Surname</th>
                    <th>Firstname</th>
                    <th>Interview</th>
                    <th>Technology</th>
                    <th>Test result</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody> 
           <!-- Candidate list ITEM -->   
           <?php foreach ($this->candidates as $candidate) {  ?> 
              <tr>
                <!--<td><?php echo $candidate->getid_kandidat(); ?></td>-->
                <td><?php echo $candidate->getprijmeni(); ?></td>
                <td><?php echo $candidate->getjmeno(); ?></td>
                <td><?php $datum = new Zend_Date($candidate->getdatum_pohovoru()); 
                    echo $datum->get(Zend_Date::DATE_MEDIUM, 'cs_CZ')?></td>
                <td><?php $technologie = $candidate->getTechnologies();
                      $tech = array();
                      foreach ($technologie as $t) {
                        $tech[] = $t->getnazev();
                      }
                      echo implode (', ', $tech)?></td>
                <td>--%</td>
                <td><?php echo $candidate->getStatus()->getnazev(); ?></td>
                <td>
                  <a href="candidate-detail"><button type="button" class="btn btn-success btn-sm">Detail</button></a>  
                </td>
              </tr>
              <?php }  //END foreach $candidate?> 
              </tbody>
            </table>
            </div><!-- /.box-body --> 
          <?php 
          // end of table
 
// haluz konstrukce, ktera vypise tenhle skript na konec souboru        
$script = <<<'JS'
$(document).ready(function() {
$('#candidates-list').DataTable( {
responsive: true,
columnDefs: [
{ responsivePriority: 1, targets: 0 },
{ responsivePriority: 2, targets: 2 },
{ responsivePriority: 1, targets: -1 }
] });
} );
JS;
$this->InlineScript()->appendScript($script, $type = 'text/javascript');
    
          } else { ?>
          
          <!-- Candidate list EMPTY --> 
          <div class="box-body">
            <div class="callout callout-info">
                <h4>V databázi nejsou žádní kandidáti.</h4>
                <p>Přidejte nového kandidáta ať zde není tak prázdno.</p>
            </div>
          </div>
        <?php } //END candidate list EMPTY ?>
          
        </div><!-- /.box -->
      </div>
    </div><!-- /.row (main row) -->    
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->