<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo $this->baseUrl() . "/"; ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="candidate">Kandidáti</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <a href="candidate-edit"><button type="submit" class="btn btn-success">Přidat nového kandidáta</button></a>
            <div class="box-tools">
              <div class="input-group" style="width: 150px;">
                <input type="text" name="table_search" class="form-control input-sm pull-right" placeholder="Hledat">
                <div class="input-group-btn">
                  <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
            </div>
          </div><!-- /.box-header -->
          
          <!-- Candidate list HEADER START-->
          <?php if (count($this->candidates) > 0) {?>
           <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
              <tr>
                <th>ID</th>
                <th>Jméno</th>
                <th>Příjmení</th>
                <th>Datum pohovoru</th>
                <th>Technologie</th>
                <th>Výsledek testu</th>
                <th>Stav</th>
                <th>Akce</th>
              </tr>
            
           <!-- Candidate list ITEM -->   
           <?php foreach ($this->candidates as $candidate) {  ?>    
              <tr>
                <td><?php echo $candidate->getid_kandidat(); ?></td>
                <td><?php echo $candidate->getjmeno(); ?></td>
                <td><?php echo $candidate->getprijmeni(); ?></td>
                <td><?php $datum = new Zend_Date($candidate->getdatum_pohovoru()); 
                    echo $datum->get(Zend_Date::DATE_MEDIUM, 'cs_CZ')?></td>
                <td><?php $technologie = $candidate->getTechnologies();
                      $tech = array();
                      foreach ($technologie as $t) {
                        $tech[] = $t->getnazev();
                      }
                      echo implode (', ', $tech)?></td>
                <td>--%</td>
                <td><?php echo $candidate->getStatus()->getnazev(); ?></td>
                <td>
                  <a href="candidate-detail"><button type="button" class="btn btn-success btn-sm">Detail</button></a>
                  <button type="submit" class="btn btn-danger btn-sm">Smazat</button>     
          <?php }  ?> 
          
          <!-- Candidate list HEADER END-->
                </td>
              </tr>
            </table>
            </div><!-- /.box-body -->
            
          <!-- Candidate list EMPTY -->  
          <?php } else { ?>
          <div class="box-body">
            <div class="callout callout-info">
                <h4>V databázi nejsou žádní kandidáti.</h4>
                <p>Přidejte nového kandidáta ať zde není tak prázdno.</p>
            </div>
          </div>
        <?php } ?>
          
        </div><!-- /.box -->
      </div>
    </div><!-- /.row (main row) -->

  </section><!-- /.content -->
</div><!-- /.content-wrapper -->