TRUNCATE TABLE `uzivatel`;

INSERT INTO `uzivatel` (`jmeno`, `prijmeni`, `email`, `heslo`, `admin`) VALUES
('Jan', 'Hudák', 'honza.hudak@gmail.com', 'd79ec596994bd5ca1879ba7d6a7cf490f0d9376f', 1),
('Anatoliy', 'Kybkalo', 'kybkalo.anatoliy@gmail.com', 'e5d4d60c942b0aa48ac657c0a0129536ef55db92', 1),
('Jirka', 'Hudec', 'jirrick@outlook.cz', 'cb8d3a7f8e18c504d1c27939b868fb45b8004692', 1),
('Filip', 'Fabišík', 'filip.fabisik@gmail.com', 'f8a6c4744156928c34cc7f295b2bdd28a7548c5a', 1),
('Jan', 'Černý', 'jc@cn.cz', '676126e0af3a3bddabd7e33983c9e1f8d8e5a9b0', 1);