
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="candidate"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="test">Tests</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-xs-12">
        <div class="box box-primary">

          <div class="box-header with-border">
            <div class="row">
              <div class="col-xs-2">
                <b>Name</b><br>
                <?php echo $this->test->getnazev(); ?>
              </div>
              <div class="col-xs-2">
                <b>Technology</b><br>
                <?php echo $this->technologyName; ?>
              </div>
              <div class="col-xs-2">
                <b>Seniority</b><br>
                <?php echo $this->seniorityName; ?>
              </div>
              <div class="col-xs-2">
                <b>Allotted time</b><br>
                <?php echo $this->test->getpocet_minut(); ?>
              </div>
              <div class="col-xs-2">
                <b>Number of questions</b><br>
                <?php echo $this->numberOfQuestions; ?>
              </div>
              <div class="col-xs-2">
                <b>Creator</b><br>
                <?php echo $this->creatorName; ?>
              </div>
            </div>
            
            <div class="row top30">
              <div class="col-xs-12">
                <b>Description</b><br>
                <?php echo $this->test->getpopis(); ?>
              </div>
            </div>
            
            <hr>

            <div class="row">
              <?php foreach ($this->questions as $q) { ?>
              <div class="col-xs-4 top30">
                <h4><?php echo $q->order . ") " . $q->question->getobsah(); ?></h4>
                <?php echo $q->question->getkomentar(); ?>
              <ul style="list-style-type: upper-alpha">
                <?php foreach ($q->options as $o) { ?>
                <li>
                  <?php if ($o->getspravnost())  { echo '<b style="color:green;">'; } ?>
                  <?php echo $o->getobsah(); ?>
                  <?php if ($o->getspravnost())  { echo "</b>"; } ?>
                  <br>
                  <?php echo $o->getkomentar(); ?>
                </li>
                <?php } ?>  
              </ul>
              </div>
              <?php } ?>
            </div>

        </div>
      </div>
    </div><!-- /.row (main row) -->

  </section><!-- /.content -->
</div><!-- /.content-wrapper -->