<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo $this->baseUrl() . "/"; ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-xs-12">
        <div class="box box-primary">
          <div class="box-header">
            <a href="test-edit"><button type="submit" class="btn btn-success">Add new Test</button></a>
          </div><!-- /.box-header -->
          <div class="box-body">
            <table id="candidates-list" class="table table-bordered table-hover">
              <thead>
                <tr>
                  <!--<th>ID</th>-->
                  <th>Name</th>
                  <th>Technology</th>
                  <th>Author</th>
                  <th>Created</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody> 
                <tr>
                  <td>Basic test for .NET</td>
                  <td>.NET</td>
                  <td>Miky Floska</td>
                  <td>12-9-2014</td>
                  <td>
                    <a href="#"><button type="button" class="btn btn-success btn-sm">Detail</button></a>  
                  </td>
                </tr>
                <tr>
                  <td>Basic test for .NET</td>
                  <td>.NET</td>
                  <td>Miky Floska</td>
                  <td>12-9-2014</td>
                  <td>
                    <a href="#"><button type="button" class="btn btn-success btn-sm">Detail</button></a>  
                  </td>
                </tr>
                <tr>
                  <td>Basic test for .NET</td>
                  <td>.NET</td>
                  <td>Miky Floska</td>
                  <td>12-9-2014</td>
                  <td>
                    <a href="#"><button type="button" class="btn btn-success btn-sm">Detail</button></a>  
                  </td>
                </tr>
                <tr>
                  <td>Basic test for .NET</td>
                  <td>.NET</td>
                  <td>Miky Floska</td>
                  <td>12-9-2014</td>
                  <td>
                    <a href="#"><button type="button" class="btn btn-success btn-sm">Detail</button></a>  
                  </td>
                </tr>
                <tr>
                  <td>Basic test for .NET</td>
                  <td>.NET</td>
                  <td>Miky Floska</td>
                  <td>12-9-2014</td>
                  <td>
                    <a href="#"><button type="button" class="btn btn-success btn-sm">Detail</button></a>  
                  </td>
                </tr>
              </tbody>
            </table>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>
    </div>

  </section><!-- /.content -->
</div><!-- /.content-wrapper -->