<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo $this->baseUrl() . "/"; ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-xs-12">
        <div class="box box-primary">
          <div class="box-header">
            <a href="test-edit"><button type="submit" class="btn btn-success">Add new Test</button></a>
          </div><!-- /.box-header -->
          <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Date</th>
                <th>Categories</th>
                <th>Action</th>
              </tr>
              <tr>
                <td>28</td>
                <td>Základy .NET</td>
                <td>12-9-2014</td>
                <td><span class="label label-success">Programování</span></td>
                <td>
                  <button type="submit" class="btn btn-success btn-sm">Edit</button>
                  <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </td>
              </tr>
              <tr>
                <td>30</td>
                <td>Git-ování</td>
                <td>18-1-2014</td>
                <td><span class="label label-success">Programování</span></td>
                <td>
                  <button type="submit" class="btn btn-success btn-sm">Edit</button>
                  <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </td>
              </tr>
              <tr>
                <td>34</td>
                <td>Front-End</td>
                <td>01-7-2015</td>
                <td><span class="label label-success">Programování</span></td>
                <td>
                  <button type="submit" class="btn btn-success btn-sm">Edit</button>
                  <button type="submit" class="btn btn-danger btn-sm">Dekete</button>
                </td>
              </tr>
              <tr>
                <td>38</td>
                <td>Základy jadrovej fyziky</td>
                <td>18-9-2015</td>
                <td><span class="label label-primary">Fyzika</span></td>
                <td>
                  <button type="submit" class="btn btn-success btn-sm">Edit</button>
                  <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </td>
              </tr>
              <tr>
                <td>55</td>
                <td>Microsof Office</td>
                <td>17-9-2015</td>
                <td><span class="label label-danger">Administrativa</span></td>
                <td>
                  <button type="submit" class="btn btn-success btn-sm">Edit</button>
                  <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </td>
              </tr>
              <tr>
                <td>59</td>
                <td>Pohoda</td>
                <td>11-11-2015</td>
                <td><span class="label label-danger">Administrativa</span></td>
                <td>
                  <button type="submit" class="btn btn-success btn-sm">Edit</button>
                  <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </td>
              </tr>
            </table>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>
    </div>

  </section><!-- /.content -->
</div><!-- /.content-wrapper -->