<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo $this->baseUrl() . "/"; ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content"> 
    <div class="row">
     
     <?php if (count($this->messages)){ ?>
    <!-- flashMesenger -->
    <?php foreach ($this->messages as $message) { ?>
      <div class="callout callout-info">
         <h4><?php echo $this->escape($message); ?></h4>
      </div>
    <?php } }; ?>

    <div class="col-md-6">
        <div class="box box-primary min-420">
          <div class="box-body box-profile">
            <ul class="list-group list-group-unbordered">
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Test: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->test->getnazev()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div>
                  <div class="flleft min-100"><b>Candidate: </b></div>
                  <div class="flleft"><a><?php echo $this->escape($this->candidate); ?></a></div>
                </div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Time alotted: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->test->getpocet_minut()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Questions: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->test->getpocet_otazek()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Status: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->status->getnazev()); ?></a></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
     
     <?php //TODO - this is just a placeholder :) ?>
     
      <div class="col-md-6">
        <div class="box box-primary">
          <div class="box-header with-border">
            <div class="row">
              <h4 class="test-h4">Questions:</h4>
              <?php foreach ($this->test->getQuestions() as $q) { ?>
              <div class="col-xs-12">
                <h4><?php echo $q->getobsah(); ?></h4>
                <?php echo $q->getkomentar(); ?>
              <ul style="list-style-type: upper-alpha">
                <?php foreach ($q->getOptions() as $o) { ?>
                <li>
                  <?php if ($o->getspravnost())  { echo '<b style="color:green;">'; } ?>
                  <?php echo $o->getobsah(); ?>
                  <?php if ($o->getspravnost())  { echo "</b>"; } ?>
                  <br>
                  <?php echo $o->getkomentar(); ?>
                </li>
                <?php } ?>  
              </ul>
              </div>
              <?php } ?>
            </div>

        </div>
      </div>
    </div><!-- /.row (main row) -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->

