<?php /* DETAIL - INTERNAL
Pro prihlasene uzivatele je zobrazen seznam otazek, tak jak je vyplnil kandidat
*/?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo $this->baseUrl() . "/"; ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content"> 
    <div class="row">
     
     <?php if (count($this->messages)){ ?>
    <!-- flashMesenger -->
    <?php foreach ($this->messages as $message) { ?>
      <div class="callout callout-info">
         <h4><?php echo $this->escape($message); ?></h4>
      </div>
    <?php } }; ?>

    <div class="col-md-6">
        <div class="box box-primary min-420">
          <div class="box-body box-profile">
            <ul class="list-group list-group-unbordered">
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Test: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->test->getnazev()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div>
                  <div class="flleft min-100"><b>Candidate: </b></div>
                  <div class="flleft"><a><?php echo $this->escape($this->candidate); ?></a></div>
                </div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Time alotted: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->test->getpocet_minut()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Questions: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->test->getpocet_otazek()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Status: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->status->getnazev()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Sumbitted: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->assignment->getdatum_vyplneni()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Result: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->assignment->gethodnoceni()); ?>%</a></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
       
      <div class="col-md-6">
        <div class="box box-primary">
          <div class="box-header with-border">
            <div class="row">
              <h4 class="test-h4">Responses:</h4>
              
              <?php 
              
              // zjednodussi a prevede jednodimenzionalni pole na multidimenzionalni
              $array = $this->assignment->getResponses(); 
              $questions = array();
              foreach ($array as $row)
              {
                $questions[$row['id_otazka']][$row['id_moznost']] = $row;
              }
              
              // projde pole pres otazky
              foreach($questions as $que_id => $que_value){
                $que = My_Model::get('Questions')->getById($que_id);?>
              <div class="col-xs-12">
                <h4><?php echo $que->getobsah(); ?></h4>
                <?php echo $que->getkomentar(); ?>
              <ul style="list-style-type: upper-alpha">
                <?php 
                // projde pole pres moznosti
                foreach ($que_value as $opt_id => $opt_value) { 
                  $opt = My_Model::get('Options')->getById($opt_id);?>
                <li>
                  <?php if ($opt_value['vyplneno'])  {
                    if ($opt_value['spravne']) 
                    // kandidat vyplnil spravne
                    {
                      echo '<span class="positive-positive">';
                    } else 
                    // kandidat vyplnil spatne
                    {
                      echo '<span class="positive-negative">';
                    }
                  } else {
                    if ($opt_value['spravne']) 
                    // kandidat nevyplnil a ani nemel vyplnit
                    {
                      echo '<span class="negative-positive">';
                    } else 
                    // kandidat nevyplnil ale mel vyplnit
                    {
                      echo '<span class="negative-negative">';
                    }
                  }
                  echo $opt->getobsah(); 
                  echo '</span>'; ?>
                  <br>
                  <?php echo $opt->getkomentar(); ?>
                </li>
                <?php } ?>  
              </ul>
              </div>
              <?php } ?>
            </div>

        </div>
      </div>
    </div><!-- /.row (main row) -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->

