<?php /* EVALUATE - INTERNAL
Pro prihlasene uzivatele je zobrazen seznam otazek, tak jak je vyplnil kandidat a uzivatel je ohodnoti
*/?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo $this->baseUrl() . "/"; ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content"> 
    <div class="row">
     
     <?php if (count($this->messages)){ ?>
    <!-- flashMesenger -->
    <?php foreach ($this->messages as $message) { ?>
      <div class="callout callout-info">
         <h4><?php echo $this->escape($message); ?></h4>
      </div>
    <?php } }; ?>
    
    <?php 
    // zjednodussi a prevede jednodimenzionalni pole na multidimenzionalni
    $array = $this->assignment->getResponses(); 
    $questions = array();
    foreach ($array as $row)
    {
      $questions[$row['id_otazka']][$row['id_moznost']] = $row;
    } 
    ?>

    <div class="col-md-4">
        <div class="box box-primary min-420">
          <div class="box-body box-profile">
            <ul class="list-group list-group-unbordered">
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Test: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->test->getnazev()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div>
                  <div class="flleft min-100"><b>Candidate: </b></div>
                  <div class="flleft"><a><?php echo $this->escape($this->candidate); ?></a></div>
                </div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Time alotted: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->test->getpocet_minut()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Questions: </b></div>
                <div class="flleft"><a><?php echo $this->escape(count($questions)); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Status: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->status->getnazev()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Sumbitted: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->assignment->getdatum_vyplneni()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Result: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->assignment->gethodnoceni()); ?>%</a></div>
              </li>
            </ul>
            <!-- Create/Edit form -->
            <?php echo $this->form; ?>
          </div>
        </div>
      </div>
       
      <div class="col-md-8">
        <div class="box box-primary">
          <div class="box-header with-border">
            <div class="row">
              <h4 class="test-h4">Responses:</h4>
              
              <?php 
              // projde pole pres otazky
              foreach($questions as $que_id => $que_value){
                $que = My_Model::get('Questions')->getById($que_id);
                $language = $que->getLanguage(); ?>
              <div class="col-xs-12">
                 <?php if ($language === null) {
                    ?><div class="question-text"><?php echo $this->escape($que->getobsah());?></div> <?php
                  } else {
                    ?><pre><code class="language-<?php echo $language->getkod(); ?>"><?php echo $this->escape($que->getobsah()); ?></code></pre> <?php
                  } ?>
                <?php echo $que->getkomentar(); ?>
              <div class="flleft question_status">
              <span id="status-q<?php echo $que_id?>"></span>
              </div>
              <div class="flleft question_options">
                <ul style="list-style-type: upper-alpha">
                    <?php 
                    // projde pole pres moznosti
                    foreach ($que_value as $opt_id => $opt_value) { 
                        if ($opt_id == NULL) { // Otevrena odpoved
                            echo '<textarea disabled>'.$opt_value['slovni_odpoved'].'</textarea>';
                        } else { // ABCD otazka
                            $opt = My_Model::get('Options')->getById($opt_id);?>
                            <li>
                            <input type="checkbox" <?php if ($opt_value['vyplneno']) { echo 'checked="checked"'; } ?> disabled>
                           <?php
                            if ($language === null) {
                                ?><span class="option-text"><?php echo $this->escape($opt->getobsah());?></span> <?php
                            } else {
                                ?><code class="language-<?php echo $language->getkod(); ?>"><?php echo $this->escape($opt->getobsah()); ?></code> <?php
                            }
                            //spravnost moznosti
                            echo '<span id="correct-q'.$que_id.'" style="display: none">'; 
                            if ($opt_value['spravne'])  {
                               echo '<span id="subcorrect-q'.$que_id.'" class="positive-positive">';
                            } else {
                                echo '<span id="subcorrect-q'.$que_id.'" class="positive-negative">';
                            }
                            echo '</span></span>'; ?>
                            
                            <br>
                            <?php echo $opt->getkomentar(); ?>
                            </li>
                            <?php }
                    } ?>  
                </ul>
              </div>
              <div class="flleft question_buttons">
                    <button id="evaluation-q<?php echo $que_id?>" class="btn btn-sm btn-block btn-info" onclick='$.showAnswers("<?php echo $que_id?>")'>Evaluation</button> 
                    <button id="correct-q<?php echo $que_id?>" class="btn btn-sm btn-block btn-success" onclick='$.evaluateQuestion("<?php echo $que_id?>",true)' style="display: none">Correct</button>
                    <button id="wrong-q<?php echo $que_id?>" class="btn btn-sm btn-block btn-warning" onclick='$.evaluateQuestion("<?php echo $que_id?>",false)' style="display: none">Wrong</button> 
              </div>
              </div>
              <?php } ?>
            </div>

        </div>
      </div>
    </div><!-- /.row (main row) -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->

