  <?php /* FILL - EXTERNAL
Kandidatovi umozni vyplnit a odeslat test.
(Musi byt JS validace testu, kvuli EULE mi nefunguje http vraceni predvyplneneho formulare)
*/?>

<!-- Content Header (Page header) -->
  <section class="content-header-ext">  
    <img class="ext-own-logo" src="<?php echo $this->baseUrl() . "/dist/img/logo-black.png"; ?>" alt="logo" />
  </section>

  <!-- Main content -->
  <section class="content"> 
    <div class="row">
     
     <?php if (count($this->messages)){ ?>
    <!-- flashMesenger -->
    <?php foreach ($this->messages as $message) { ?>
      <div class="callout callout-info">
         <h4><?php echo $this->escape($message); ?></h4>
      </div>
    <?php } }; ?>

    <div class="col-md-6 col-md-offset-3">
      <h1 class="main-h1"><?php echo $this->escape($this->title); ?></h1>
      <div class="callout callout-info">
        <h4><?php echo $this->test->nazev;?></h4>
        <p><?php echo $this->test->popis;?></p>
      </div>  

        
      <!-- Test fill form -->
    <?php echo $this->form; ?>
       
  
      <div class="callout callout-warning" id="error-box"></div>
      
<?php      
// haluz konstrukce, ktera vypise tenhle skript na konec souboru        
$script = <<<'JS'
$('#fillTest').validate({
submitHandler: function(form) {
$("#submit").attr('disabled', 'disabled');
form.submit();
},
showErrors: function(errorMap, errorList) {
$("#error-box").html("You must select at least one option for each checkbox question or type at least three letters in textareas.");
},
onchange: true,         
wrapper: "p"
});

jQuery.validator.addClassRules({
  "question-options": {
    required: true,
    minlength: 1
  },
  "question-answer": {
    required: true,
    minlength: 3
  }
});
JS;
$this->InlineScript()->appendScript($script, $type = 'text/javascript');   
?>  

      </div>
    </div><!-- /.row (main row) -->
  </section><!-- /.content -->
