<div >    
   
   <h2>
      <?php echo $this->escape($this->title); ?>
    </h2>
    
     <?php if (count($this->messages)){ ?>
    <!-- flashMesenger -->
    <?php foreach ($this->messages as $message) { ?>
      <div class="callout callout-info">
         <h4><?php echo $this->escape($message); ?></h4>
      </div>
    <?php } }; ?>


    <h3>
     TEST: <?php echo $this->escape($this->test); ?>
    </h3>
    
    <h3>
     CANDIDATE: <?php echo $this->escape($this->candidate); ?>
    </h3>


    <form action="<?php echo $this->url(array('controller' => 'assignment',
                                            'action' => 'submit' )); ?>"
                       method="post"><input type="submit" class="btn btn-success btn-sm" value="Test submit"/>
	


</div>