<?php /* TEST - INTERNAL
Pro prihlasene uzivatele je zobrazen seznam otazek, ktere by se nabidly kandidatovi k vyplneni.
*/?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo $this->baseUrl() . "/"; ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content"> 
    <div class="row">
     
     <?php if (count($this->messages)){ ?>
    <!-- flashMesenger -->
    <?php foreach ($this->messages as $message) { ?>
      <div class="callout callout-info">
         <h4><?php echo $this->escape($message); ?></h4>
      </div>
    <?php } }; ?>

    <div class="col-md-5">
        <div class="box box-primary min-420">
          <div class="box-body box-profile">
            <ul class="list-group list-group-unbordered">
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Test: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->test->getnazev()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div>
                  <div class="flleft min-100"><b>Candidate: </b></div>
                  <div class="flleft"><a><?php echo $this->escape($this->candidate); ?></a></div>
                </div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Time alotted: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->test->getpocet_minut()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Questions: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->test->getpocet_otazek()); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Status: </b></div>
                <div class="flleft"><a><?php echo $this->escape($this->status->getnazev()); ?></a></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
     
      <div class="col-md-7">
        <div class="box box-primary">
          <div class="box-header with-border">
            <div class="row">
              <h4 class="test-h4">Questions:</h4>
              <?php  // Questions 
              foreach ($this->test->getQuestions() as $q) { ?>
              <div class="col-xs-12">
                <div class="eva-q">
                <?php $language = $q->getLanguage();
                if ($language === null) {
                    ?><span class="question-text own-qt"><?php echo $this->escape($q->getobsah());?></span> <?php
                } else {
                    ?><pre><code class="language-<?php echo $language->getkod(); ?>"><?php echo $this->escape($q->getobsah()); ?></code></pre> <?php
                } ?>
                <?php echo $q->getkomentar(); ?>
              <ul style="list-style-type: upper-alpha">
                <?php //Options
                foreach ($q->getOptions() as $o) { ?>
                <li>
                  <?php if ($o->getspravnost())  { echo '<span class="positive-positive">'; } ?>
                  <?php 
                    if ($language === null) {
                        ?><span class="option-text"><?php echo $this->escape($o->getobsah());?></span> <?php
                    } else {
                        ?><code class="language-<?php echo $language->getkod(); ?>"><?php echo $this->escape($o->getobsah()); ?></code> <?php
                    } ?>
                  <?php if ($o->getspravnost())  { echo "</span>"; } ?>
                  <br>
                  <?php echo $o->getkomentar(); ?>
                </li>
                <?php } ?>
                <?php //pokud neni zadna moznost - tak se zobrazi textbox
                if (count($q->getOptions()) == 0) echo '<input type="text" value="Open question" disabled>'; ?>    
              </ul>
              </div>
              </div>
              <?php } ?>
            </div>

        </div>
      </div>
    </div><!-- /.row (main row) -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->

