<?php
 
	echo $this->doctype();
	
?>

<html xmlns="http://www.w3.org/1999/xhtml">
	
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title><?php echo $this->title; ?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

		<?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/global.css'); ?>
		<?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/admin.css'); ?>

	</head>
	
	<body>
		
    
    <div class="container">            

		<!-- Hlavicka -->
      <?php echo $this->render('header-admin.phtml') ?>
		
      <?php echo $this->messages(); ?>				
					<?php echo $this->layout()->content; ?>
					
		<!-- Paticka -->
		<?php echo $this->render('footer.phtml') ?>

    </div>
		
	</body>
	
</html>    