<footer class="main-footer">
	<div class="pull-right hidden-xs foot-ed">
		<strong>Copyright &copy; 2015 <a href="<?php echo $this->baseUrl() . "/"; ?>">4it445.vse.cz</a>.</strong> All rights reserved. <b>Version</b> beta 1.0.1
	</div>
	Created by 
	<img class="foot-logo" src="<?php echo $this->baseUrl() . "/dist/img/cnlogo.jpg"; ?>">
	<img class="foot-logo" src="<?php echo $this->baseUrl() . "/dist/img/vselogo.png"; ?>">
</footer>