<header class="main-header">
	<!-- Logo -->
	<a href="<?php echo $this->baseUrl() . "/"; ?>" class="logo">
	  <!-- mini logo for sidebar mini 50x50 pixels -->
	  <span class="logo-mini"><img class="own-logo" src="<?php echo $this->baseUrl() . "/dist/img/logo-mini.png"; ?>" alt="minilogo" /></span>
	  <!-- logo for regular state and mobile devices -->
	  <span class="logo-lg"><img class="own-logo" src="<?php echo $this->baseUrl() . "/dist/img/logo.png"; ?>" alt="logo" /></span>
	</a>
	<!-- Header Navbar: style can be found in header.less -->
	<nav class="navbar navbar-static-top" role="navigation">
	  <!-- Sidebar toggle button-->
	  <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
	    <span class="sr-only">Toggle navigation</span>
	  </a>
	  <div class="navbar-custom-menu">
	    <ul class="nav navbar-nav">
	      
	      <!-- User Account: style can be found in dropdown.less -->
	      <li class="dropdown user user-menu">
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown">

	          <img src="<?php echo $this->baseUrl() . "/dist/img/user2-160x160.jpg"; ?>" class="user-image" alt="User Image">

                  <span class="hidden-xs">
                      
                      <?php      
                            if($this->user != null){
                                echo $this->user->jmeno." ".$this->user->prijmeni;
                            }
                        ?>
                      
                  </span>
	        </a>
	        <ul class="dropdown-menu">
	          <!-- User image -->
	          <li class="user-header">
	            <img src="<?php echo $this->baseUrl() . "/dist/img/user2-160x160.jpg"; ?>" class="img-circle" alt="User Image">
	            <p>
	             
                        <?php      
                            if($this->user != null){
                                echo $this->user->jmeno." ".$this->user->prijmeni;
                            }
                        ?>
                        
	              <small>
                          
                          <?php      
                            if($this->user != null){
                                echo $this->user->email;
                            }
                        ?>
                      
                      
                      </small>
	            </p>
	          </li>
	          <!-- Menu Body -->
	          <li class="user-body">
	            <div class="col-xs-4 text-center">
	              <a href="#">Followers</a>
	            </div>
	            <div class="col-xs-4 text-center">
	              <a href="#">Sales</a>
	            </div>
	            <div class="col-xs-4 text-center">
	              <a href="#">Friends</a>
	            </div>
	          </li>
	          <!-- Menu Footer-->
	          <li class="user-footer">
	            <div class="pull-left">
	              <a href="#" class="btn btn-default btn-flat">Profile</a>
	            </div>
	            <div class="pull-right">
	              <a href="logout" class="btn btn-default btn-flat">Sign out</a>
	            </div>
	          </li>
	        </ul>
	      </li>
	      <!-- Control Sidebar Toggle Button -->
	      <li>
	        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
	      </li>
	    </ul>
	  </div>
	</nav>
</header>