<div class="header">
<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
    <ul class="nav nav-pills pull-right">     
    
    	   <li><a href="<?php echo $this->url(
						            array('controller' => 'admin'), 
						            'default', 
						            true) ?>">Úvod</a></li>
						            
				<li><a href="<?php echo $this->url(
						            array('controller' => 'product',
						            	  'action' => 'list'), 
						            'default', 
						            true) ?>">Produkty</a></li>
        
        <li><a href="<?php echo $this->url(
						            array(), 'logout', true)
						            ?>">Odhlásit</a></li>

                          
    </ul>
<?php endif; ?>

    <h3 class="text-muted"><a href="<?php echo $this->url(
						            array('controller' => 'admin'), 
						            'default', 
						            true) ?>">Administrace</a></h3>
</div>