<?php echo $this->doctype(); ?>

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="favicon.ico" type="<?php echo $this->baseUrl() . "/dist/img/favicon.ico"; ?>"/>
    <title>Interview.me | <?php echo $this->escape($this->title);?></title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/bootstrap/css/bootstrap.min.css"; ?>">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/dt/dt-1.10.10,fh-3.1.0,r-2.0.0,sc-1.4.0/datatables.min.css"/>
    <!--<link rel="stylesheet" href="<?php echo $this->baseUrl() . "/plugins/datatables/dataTables.bootstrap.css"; ?>">-->
    <!-- Select 2 form element -->
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/dist/css/AdminLTE.css"; ?>">

    <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/dist/css/AdminLTE-add.css"; ?>">
    <!-- Prism CSS-->
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/dist/css/prism.css"; ?>">
    <!-- jQuery-UI -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/dist/css/skins/_all-skins.min.css"; ?>">
    <!-- iCheck -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/plugins/iCheck/flat/blue.css"; ?>">
    <!-- Morris chart -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/plugins/morris/morris.css"; ?>">
    <!-- jvectormap -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/plugins/jvectormap/jquery-jvectormap-1.2.2.css"; ?>">
    <!-- Date Picker -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/plugins/datepicker/datepicker3.css"; ?>">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/plugins/daterangepicker/daterangepicker-bs3.css"; ?>">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css"; ?>">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->    
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

    	<?php echo $this->render('header.phtml') ?>
      
      	<?php echo $this->render('navigation.phtml') ?>
      
      	<?php echo $this->layout()->content; ?>
      
      	<?php echo $this->render('footer.phtml') ?>

      	<?php echo $this->render('control.phtml') ?>
      
    </div><!-- ./wrapper -->

    <!-- jQuery 2.1.4 -->
    <script src="<?php echo $this->baseUrl() . "/plugins/jQuery/jQuery-2.1.4.min.js"; ?>"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.5 -->
    <script src="<?php echo $this->baseUrl() . "/bootstrap/js/bootstrap.min.js"; ?>"></script>

    <!-- DataTables -->
    <script type="text/javascript" src="https://cdn.datatables.net/s/dt/dt-1.10.10,fh-3.1.0,r-2.0.0,sc-1.4.0/datatables.min.js"></script>
    <!--<script src="<?php echo $this->baseUrl() . "/plugins/datatables/jquery.dataTables.min.js"; ?>"></script>
    <script src="<?php echo $this->baseUrl() . "/plugins/datatables/dataTables.bootstrap.min.js"; ?>"></script>-->

    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="<?php echo $this->baseUrl() . "/plugins/morris/morris.min.js"; ?>"></script>
    <!-- Sparkline -->
    <script src="<?php echo $this->baseUrl() . "/plugins/sparkline/jquery.sparkline.min.js"; ?>"></script>
    <!-- jvectormap -->
    <script src="<?php echo $this->baseUrl() . "/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"; ?>"></script>
    <script src="<?php echo $this->baseUrl() . "/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"; ?>"></script>
    <!-- jQuery Knob Chart -->
    <script src="<?php echo $this->baseUrl() . "/plugins/knob/jquery.knob.js"; ?>"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
    <script src="<?php echo $this->baseUrl() . "/plugins/daterangepicker/daterangepicker.js"; ?>"></script>
    <!-- datepicker -->
    <script src="<?php echo $this->baseUrl() . "/plugins/datepicker/bootstrap-datepicker.js"; ?>"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="<?php echo $this->baseUrl() . "/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"; ?>"></script>
    <!-- Slimscroll -->
    <script src="<?php echo $this->baseUrl() . "/plugins/slimScroll/jquery.slimscroll.min.js"; ?>"></script>
    <!-- FastClick -->
    <script src="<?php echo $this->baseUrl() . "/plugins/fastclick/fastclick.min.js"; ?>"></script>
    <!-- AdminLTE App -->
    <script src="<?php echo $this->baseUrl() . "/dist/js/app.min.js"; ?>"></script>
    <!-- Prism JS -->
    <script src="<?php echo $this->baseUrl() . "/dist/js/prism.js"; ?>"></script>
    <!-- Select 2 form element -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js"></script>

    <!-- Custom Scripts -->
    <script src="<?php echo $this->baseUrl() . "/dist/js/custom.js"; ?>"></script>


    <?php echo $this->InlineScript(); ?>

  </body>
</html>