<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li><a href="<?php echo $this->url(array('controller' => 'test', 'action' => 'index'), 'default', true); ?>"><i class="fa fa-files-o"></i> <span> Tests</span></a></li>
      <li><a href="<?php echo $this->url(array('controller' => 'candidate', 'action' => 'index'), 'default', true); ?>"><i class="fa fa-child"></i> <span> Candidates</span></a></li>
      <li><a href="<?php echo $this->url(array('controller' => 'stat', 'action' => 'index'), 'default', true); ?>"><i class="fa fa-pie-chart"></i> <span>Statistics</span></a></li>
      <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index'), 'default', true); ?>"><i class="fa fa-users"></i> <span>Users</span></a></li>
     </ul>
  </section>
  <!-- /.sidebar -->
</aside>