<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <!-- search form -->
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
      </div>
    </form>
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li><a href="index.php"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
      <li class="treeview"> <!-- POZOR! zmenit classu na "tree active" ak je aktualna stranka ohladom testov -->
        <a href="#">
          <i class="fa fa-files-o"></i>
          <span>Testy</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><a href="test"><i class="fa fa-circle-o"></i> Seznam testů</a></li>
          <li><a href="test-edit"><i class="fa fa-circle-o"></i> Přidat nový test</a></li>
          <li><a href="test-result"><i class="fa fa-circle-o"></i> Výsledky testů</a></li>
        </ul>
      </li>
      <li class="treeview"><!-- POZOR! zmenit classu na "tree active" ak je aktualna stranka ohladom kandidatov -->
        <a href="#">
          <i class="fa fa-users"></i>
          <span>Kandidáti</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><a href="candidate"><i class="fa fa-circle-o"></i> Seznam kandidátů</a></li>
          <li><a href="candidate-edit"><i class="fa fa-circle-o"></i> Přidat nového kandidáta</a></li>
        </ul>
      </li>
      <li><a href="stat"><i class="fa fa-pie-chart"></i> <span>Statistiky</span></a></li>
      <li><a href="about"><i class="fa fa-info-circle"></i> <span>O aplikaci</span></a></li>
  </section>
  <!-- /.sidebar -->
</aside>