<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo $this->baseUrl() . "/"; ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index'), 'default', true); ?>">Users</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    
    
    <?php if (count($this->messages)){ ?>
    <!-- flashMesenger -->
    <?php foreach ($this->messages as $message) { ?>
      <div class="callout callout-info">
         <h4><?php echo $this->escape($message); ?></h4>
      </div>
    <?php } }; ?>
   
    
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-md-4">
        <div class="box box-primary">
          <div class="box-body box-profile">
            <?php if ($this->detailavatarBase64 !== NULL) { ?>
            <?php echo '<img class="profile-user-img img-responsive img-circle" src="data:image/gif;base64,' . $this->detailavatarBase64 . '"  />'?>
            <?php } else { ?>
              <img class="profile-user-img img-responsive img-circle" src="<?php echo $this->baseUrl() . "/dist/img/avatar5.png"; ?>" alt="User profile picture">
            <?php } ?>
          </div>
        </div>
      </div>

      <div class="col-md-8">
        <div class="box box-primary">
          <div class="box-body box-profile">
            <ul class="list-group list-group-unbordered">
              <li class="list-group-item min-42">
                <div class="flleft min-100"><b>Firstname: </b></div>
                <div class="flleft"><a><?php echo $this->detailuser->getjmeno(); ?></a></div>
              </li>
              <li class="list-group-item min-42">
                <div>
                  <div class="flleft min-100"><b>Surename: </b></div>
                  <div class="flleft"><a><?php echo $this->detailuser->getprijmeni(); ?></a></div>
                </div>
              </li>
              <li class="list-group-item min-42">
                <div>
                  <div class="flleft min-100"><b>Email: </b></div>
                  <div class="flleft"><a><?php echo $this->detailuser->getemail(); ?></a></div>
                </div>
              </li>
              <li class="list-group-item min-42">
                <div>
                  <div class="flleft min-100"><b>Role: </b></div>
                  <div class="flleft"><a><?php echo ($this->detailuser->isAdmin() ? 'Administrator' : 'Reviewer') ?></a></div>
                </div>
              </li>
            </ul>

            <div class="row">
              <div class="col-xs-6">
                <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index', 'id' => NULL)); ?>"><button type="button" class="btn btn-default ">Back</button></a>
              </div>
              <div class="col-xs-6 text-right">
                <a href="<?php echo $this->url(array('controller' => 'user', 'id' => $this->detailuser->getid_uzivatel(), 'action' => 'edit')); ?>"><button type="button" class="btn btn-success">Edit User</button></a>
              </div>
            </div>
          </div>
        </div>
        </div>

        <div class="clearfix"></div>

      </div>
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->