<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->escape($this->title); ?>
    </h1>
    <ol class="breadcrumb">
      <li><a href="<?php echo $this->baseUrl() . "/"; ?>"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="<?php echo $this->url(array('controller' => 'candidate', 'action' => 'index'), 'default', true); ?>">Candidates</a></li>
      <li class="active"><?php echo $this->escape($this->title); ?></li>
    </ol>
  </section>

    <!-- Main content -->
  <section class="content">

    <!-- Create/Edit form -->
    <?php echo $this->form; ?>

  </section><!-- /.content -->
</div><!-- /.content-wrapper -->


<?php 
// Appends Javascript at the end of file
$script = <<<'JS'
$(document).ready(function () {
    $( ".date-picker" ).datepicker({ dateFormat: 'yy-mm-dd' });
    $('#kandidat_technologie').select2();
});
JS;
$this->InlineScript()->appendScript($script, $type = 'text/javascript');
?>