<div class="box box-primary">
  <div class="box-header">
  	<?php if ($this->user->isAdmin()) { ?>
	    <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'registration')); ?>"><button type="submit" class="btn btn-success">Add new User</button></a>
    <?php } ?>
  </div><!-- /.box-header -->
  
  <!-- User list HEADER-->
  <?php if (count($this->users) > 0) {?>
   <div class="box-body">
      <table id="users-list" class="table table-bordered table-hover">
        <thead>
          <tr>
            <!--<th>ID</th>-->
            <th>Name</th>
            <th>Role</th>
            <th class="text-right">Actions</th>
          </tr>
        </thead>
        <tbody> 
   <!-- User list ITEM -->   
   <?php foreach ($this->users as $user) {  ?> 
      <tr>
        <td><?php echo $user->getFullName(); ?></td>
        <td>
            <?php if ($user->isAdmin()) { ?>
            <i class="fa fa-rocket"></i>&nbsp;&nbsp;Administrator
            <?php } else { ?> 
            <i class="fa fa-edit"></i>&nbsp;&nbsp;Reviewer
            <?php } ?>
        </td>
        <td class="text-right">
            <?php if ($user->isAdmin()) { ?>
                <a class="replace-users-list" href="<?php echo $this->url(array('controller' => 'user', 'id' => $user->getid_uzivatel(), 'action' => 'toggle-admin-role')); ?>"><button type="button" class="btn btn-default btn-sm"><i class="fa fa-magic"></i>&nbsp;&nbsp;Reviewer</button></a>  
            <?php } else { ?> 
                <a class="replace-users-list" href="<?php echo $this->url(array('controller' => 'user', 'id' => $user->getid_uzivatel(), 'action' => 'toggle-admin-role')); ?>"><button type="button" class="btn btn-default btn-sm"><i class="fa fa-magic"></i>&nbsp;&nbsp;Administrator</button></a>  
            <?php } ?>

            <a class="delete-user" href="<?php echo $this->url(array('controller' => 'user', 'id' => $user->getid_uzivatel(), 'action' => 'delete')); ?>"><button type="button" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i>&nbsp;&nbsp;Delete</button></a>

            <a href="<?php echo $this->url(array('controller' => 'user', 'id' => $user->getid_uzivatel(), 'action' => 'detail')); ?>"><button type="button" class="btn btn-success btn-sm"><i class="fa fa-smile-o"></i>&nbsp;&nbsp;Detail</button></a>  
        </td>
      </tr>
      <?php }  //END foreach $user?> 
      </tbody>
    </table>
    </div><!-- /.box-body --> 
  <?php 
  // end of table

// haluz konstrukce, ktera vypise tenhle skript na konec souboru        
$script = <<<'JS'
$(document).ready(function() {
$('#users-list').DataTable( {
responsive: false,
columnDefs: [
{ responsivePriority: 1, targets: 0 },
{ responsivePriority: 2, targets: 2 },
{ responsivePriority: 1, targets: -1 },
{ bSortable: false, aTargets: -1 }
] });
} );
JS;
$this->InlineScript()->appendScript($script, $type = 'text/javascript');

  } else { ?>
  
  <!-- Candidate list EMPTY --> 
  <div class="box-body">
    <div class="callout callout-info">
        <h4>There are no users to show</h4>
        <p>Enter new users to hide this annoying message :)</p>
    </div>
  </div>
<?php } //END candidate list EMPTY ?>
  
</div><!-- /.box -->