<form action="<?php echo $this->element->getAction(); ?>" method="<?php echo $this->element->getMethod(); ?>" enctype="multipart/form-data">
	
	<div class="row">
		<div class="col-md-4">
			<div class="box box-primary">
				<div class="box-body box-profile">

					<?php if ($this->element->avatar->getAttrib('src') !== NULL) { ?>
					<?php echo $this->element->avatar; ?>
					<?php } else { ?>
					<img class="profile-user-img img-responsive img-circle" src="<?php echo $this->baseUrl() . "/dist/img/avatar5.png"; ?>" alt="User profile picture">
					<?php } ?>

					<div class="form-group">
						<label>Insert profile picture</label>
						<?php echo $this->element->profilePhoto; ?>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-8">
			<div class="box box-primary">
				<div class="box-body box-profile">
					<div class="form-group">
						<label>Firstname</label>
						<?php echo $this->element->jmeno; ?>
					</div>

					<div class="form-group">
						<label for="prijmeni">Surname</label>
						<?php echo $this->element->prijmeni; ?>
					</div>

					<div class="form-group">
						<label for="prijmeni">E-mail</label>
						<?php echo $this->element->email; ?>
					</div>

					<div class="row">
						<div class="col-xs-6">
							<?php echo $this->element->closeButton; ?>
						</div>
						<div class="col-xs-6 text-right">
							<?php echo $this->element->deleteButton; ?>
							<?php echo $this->element->saveButton; ?>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</form>