<?php if (! 0 == 1) { ?>
	
	<div class="jumbotron">
        <h1><?php echo $this->escape($this->title); ?></h1>
    </div>
    
    <div class="posts">
    	<?php foreach ($this->posts as $post) { ?>
    	
    		<div class="post">
    			
    			<h2>
    				<a href="<?php echo $this->url(array ('title' => $this->escape($post[title])),
    									  'post',
    									  true); ?>">
    				<?php echo $this->escape($post[title])?>
    				</a>
    			</h2>
    			
    		</div>
    	
    	<?php } ?>
    </div>

<?php } else { ?>
    <p>Neexistuje žiadny článok.</p>
<?php } ?>